site_name: 西北工业大学舞蹈机器人基地简介
site_url: https://NPU-Home.github.io/home # 网站地址

repo_name: NPU-Home/home # 仓库名称
repo_url: https://github.com/NPU-Home/home # 仓库地址

theme:
    name: "material" # 主题名称
    language: "zh" # 网站语言
    favicon: image/ico.png # 网站图标
    icon: # 网站图标
        logo: material/home

    features: # 特性
        - content.code.annotate # 代码注释
        - navigation.tracking # 导航栏跟踪
        - navigation.tabs # 导航栏标签
        - navigation.indexes # 导航栏索引
        - navigation.top # 导航栏顶部
        - content.code.copy # 代码复制
        - content.code.annotate # 代码注释
        - navigation.footer # 导航栏底部
        - navigation.sections
        - navigation.expand #目录展开
        - navigation.path
        - toc.follow
        - content.tooltips

    palette:
        scheme: auto

    custom_dir: docs/resources

extra_css:
    - css/theme/global/fonts.css
    - css/theme/global/scheme.css
    - css/theme/global/img.css

    - css/theme/content/admonition.css
    - css/theme/content/markdown.css

    - css/theme/head/search.css
    - css/theme/head/git.css
    - css/theme/head/tab.css
    - css/theme/head/header.css

    - css/theme/foot/footer.css
    - css/theme/nav.css
    - css/theme/top.css
    - css/theme/link.css
    - css/theme/card.css
    - css/theme/button.css
    - css/theme/ico.css

    - css/img-zoom/zoom.css

    - css/enc/input.css
    - css/enc/button.css
    - css/enc/msg.css

    - css/giscus/giscus.css

extra_javascript:
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    - js/zoom.js

plugins:
    - search: {}

    - git-revision-date-localized:
          type: timeago
          custom_format: "%d. %B %Y"
          timezone: Asia/Shanghai
          locale: zh
          fallback_to_build_date: false
          enable_creation_date: true

markdown_extensions:
    - abbr # 缩写
    - pymdownx.snippets # 代码块
    - pymdownx.highlight: # 代码高亮
          anchor_linenums: true # 代码行号
    - pymdownx.inlinehilite # 行内代码高亮
    - pymdownx.superfences # 内置标题栏
    - attr_list # 属性列表
    - md_in_html

    - toc: # 目录
          # permalink: "↗" # 目录链接
          toc_depth: 4 # 目录深度
    - meta # 元数据
    - def_list # 定义列表
    - attr_list # 属性列表
    - md_in_html # HTML中的Markdown
    - sane_lists # 列表
    - admonition # 警告

    - pymdownx.keys # 键盘
    - pymdownx.mark # 标记
      # 格式化处理
    - pymdownx.caret # 上标
    - pymdownx.keys # 键盘
    - pymdownx.mark # 标记
    - pymdownx.tilde # 删除线
    - pymdownx.critic # 评论

    - pymdownx.details # 详情
    - pymdownx.magiclink # 链接
    - tables # 表格

    - meta

    - pymdownx.tabbed: # 标签
          alternate_style: true # 标签样式
    - pymdownx.tasklist: # 任务列表
          custom_checkbox: true # 自定义复选框
    - pymdownx.arithmatex: # 数学公式
          generic: true # 通用
    - pymdownx.emoji: # emoji
          emoji_index:
              !!python/name:material.extensions.emoji.twemoji # emoji索引
          emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
    - index.md
    - 项目组介绍: page/项目组/index.md
    - 方向介绍:
          - 软件组: page/方向/软件.md
          - 电子组: page/方向/电子.md
          - 机械组: page/方向/机械.md
    - 学习思路:
          - 软件学习: page/学习思路/软件组学习思路.md
